dist: xenial

sudo: false

services:
- mysql -u root -p

sudo: required
before_install:
  - mysql -u root -e 'CREATE DATABASE flyway;'
  - mysql -u root flyway < src/main/resources/db/migration/mysql/V1__tabela_empresa.sql
  - mysql -u root flyway < src/main/resources/db/migration/mysql/V2__init_empresa.sql
  - mysql -u root flyway < src/main/resources/db/migration/mysql/V3__table_company.sql
  - mysql -u root flyway < src/main/resources/db/migration/mysql/V4__init_company.sql
  - mysql -u root flyway < src/main/resources/db/migration/mysql/V5__table_user.sql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      
