dist: trusty
language: java
sudo: false
jdk:
- oraclejdk9
# would just use default install/script but the ./mvnw script errors on travis
# obviously this only works for maven builds right now...
services:
- mysql
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
sudo: required
dist: trusty
before_script:
#  - cp .env.travis .env
#  - sudo mysql -e 'CREATE DATABASE testing;'
  - mysql -u root -e 'CREATE DATABASE flyway;'
  - mysql -u root flyway < db/migration/mysql/V1__tabela_empresa.sql
  - mysql -u root flyway < db/migration/mysql/V2__init_empresa.sql
  - mysql -u root flyway < db/migration/mysql/V3__table_company.sql
  - mysql -u root flyway < db/migration/mysql/V4__init_company.sql
  - mysql -u root flyway < db/migration/mysql/V5__table_user.sql

install:
- true
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
#- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn test -B
#- mvn clean install
#- Teste
- mvn -U clean install
#addons:
#  apt:
#   sources:
#    - mysql-5.7-trusty
#   packages:
#    - mysql-server
#    - mysql-client
