
#deploy:
#  provider: script
#  script: bash ./custom-deploy.sh
before_install:
- echo pwd
- exec home/travis/.database.yml
#  - cp .env.travis .env
#  - sudo mysql -e 'CREATE DATABASE testing;'

dist: trusty
language: java
sudo: false
jdk:
- oraclejdk9
# would just use default install/script but the ./mvnw script errors on travis
# obviously this only works for maven builds right now...
      
#dist: xenial

install: 
- true
- mvn install 
- DskipTests=true 
- Dmaven.javadoc.skip=true -B -V
#- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn clean verify
#- mvn install
- mvn test -B
#- mvn clean install
#- Teste
- mvn -U clean install
#- bash build.sh || travis_terminate 40;
#- bash deploy.sh || travis_terminate 40;

notifications:
 - email: cildefonso@gmail.com
 - email: anacristinaestevesfernandes@gmail.com
 
 
# blacklist
#branches:
#  except:
#    - legacy
#    - experimental

# whitelist
#branches:
#  only:
#    - master
#    - stable
