dist: trusty
language: java
sudo: false
jdk:
- oraclejdk9
# would just use default install/script but the ./mvnw script errors on travis
# obviously this only works for maven builds right now...
services:
- mysql
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
before_script:
  - mysql -e 'create database flyway;'
#before_install:
#    - sudo mysql -e 'CREATE DATABASE flyway;'
#    - sudo mysql -e 'select database();'
#    - sudo mysql -e 'SHOW DATABASES;'
#    - sudo mysql -e 'USE flyway;'
#    - sudo mysql -e 'select database();'
#    - sudo mysql --version
install:
- true
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
#- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn test -B
#- mvn clean install
#- Teste
- mvn -U clean install
#addons:
#  apt:
#   sources:
#    - mysql-5.7-trusty
#   packages:
#    - mysql-server
#    - mysql-client
