#https://www.youtube.com/watch?v=Uft5KBimzyk
#https://www.youtube.com/watch?v=BFpSD2eoXUk
#https://www.youtube.com/watch?v=g0KsiCj3CgQ&list=PLT7ak8zxhXKjVTn3Lwc2MM4eEDfp811ys
#https://www.youtube.com/watch?v=4QjqL9zwKkI
#https://www.youtube.com/watch?v=5PQbxuK2pH4
#https://github.com/manjulaRathnayaka/API-Management-CI-CD-Example/blob/master/.travis.yml
#https://cdn.travis-ci.com/github/DanielFran/jhipster-dependencies/jobs/152090244/config
#https://www.programmersought.com/article/38541593964/
#https://medium.com/tableless/integra%C3%A7%C3%A3o-cont%C3%ADnua-com-travis-ci-parte-02-5988d6dd95db
before_script:
- ./database.yml
#  - cp .env.travis .env
#  - sudo mysql -e 'CREATE DATABASE testing;'

dist: trusty
language: java
sudo: false
jdk:
- oraclejdk9
# would just use default install/script but the ./mvnw script errors on travis
# obviously this only works for maven builds right now...
      
#dist: xenial

install: 
- true
- mvn install 
- DskipTests=true 
- Dmaven.javadoc.skip=true -B -V
#- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn clean verify
#- mvn install
- mvn test -B
#- mvn clean install
#- Teste
- mvn -U clean install
#- bash build.sh || travis_terminate 40;
#- bash deploy.sh || travis_terminate 40;

notifications:
 - email: cildefonso@gmail.com
 - email: anacristinaestevesfernandes@gmail.com
 
 
# blacklist
#branches:
#  except:
#    - legacy
#    - experimental

# whitelist
#branches:
#  only:
#    - master
#    - stable
