dist: xenial

sudo: false

services:
- mysql -u root -p

sudo: required
before_install:
  - mysql -u root -e 'CREATE DATABASE flyway;'
  - mysql -u root flyway < src/main/resources/db/migration/mysql/V1__tabela_empresa.sql
  - mysql -u root flyway < src/main/resources/db/migration/mysql/V2__init_empresa.sql
  - mysql -u root flyway < src/main/resources/db/migration/mysql/V3__table_company.sql
  - mysql -u root flyway < src/main/resources/db/migration/mysql/V4__init_company.sql
  - mysql -u root flyway < src/main/resources/db/migration/mysql/V5__table_user.sql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

dist: trusty
language: java
sudo: false
jdk:
- oraclejdk9
# would just use default install/script but the ./mvnw script errors on travis
# obviously this only works for maven builds right now...
      
#dist: xenial

install: 
- true
- mvn install 
- DskipTests=true 
- Dmaven.javadoc.skip=true -B -V
#- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn clean verify
#- mvn install
- mvn test -B
#- mvn clean install
#- Teste
- mvn -U clean install
#- bash build.sh || travis_terminate 40;
#- bash deploy.sh || travis_terminate 40;

notifications:
 - email: cildefonso@gmail.com
 - email: anacristinaestevesfernandes@gmail.com
 
 
# blacklist
#branches:
#  except:
#    - legacy
#    - experimental

# whitelist
#branches:
#  only:
#    - master
#    - stable
